name: easy_auth
description: Widgets and classes that make it easy to add authentication to any Flutter app
version: 0.1.1
homepage: https://github.com/ramseskamanda/easy_auth
repository: https://github.com/ramseskamanda/easy_auth
issue_tracker: https://github.com/ramseskamanda/easy_auth/issues
documentation: https://github.com/ramseskamanda/easy_auth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0

  very_good_analysis: ^2.1.0

  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  another_flushbar: ^1.10.22

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.0.0
  mocktail: ^0.1.0
